### ISSUE TITLE
Klipper SGP40 PR

### ISSUE THREAD

**Issue by meteyou** [thetic/klipper-sgp40#4]
Currently their is an open PR for this sensor in Klipper with some questions:

- Klipper PR: https://github.com/Klipper3d/klipper/pull/6738
- Discussion in the Klipper Discourse Forum: https://klipper.discourse.group/t/support-for-sgp40-sensors/20033

I would be happy, when you support this, to get the Sensor merged in Mainline Klipper...

**Comment by thetic** [comment]
I've ported the code from your PR to the https://github.com/thetic/klipper-sgp40/tree/upstream branch for testing. I am seeing the following error:

```
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/mcu.py", line 91, in _do_send
    return xh.get_response(cmds, self._cmd_queue, minclock, reqclock)
  File "/home/pi/klipper/klippy/serialhdl.py", line 506, in get_response
    raise error("Unable to obtain '%s' response" % (self.name,))
klippy.serialhdl.error: Unable to obtain 'i2c_read_response' response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/klipper/klippy/printer.py", line 290, in _connect
    cb()
  File "/home/pi/klipper/klippy/extras/sgp40/__init__.py", line 48, in handle_connect
    self._init_sgp40()
  File "/home/pi/klipper/klippy/extras/sgp40/__init__.py", line 67, in _init_sgp40
    serial = self._write_command(SGP40_CMD["GET_SERIAL"], read_len=6,
  File "/home/pi/klipper/klippy/extras/sgp40/__init__.py", line 127, in _write_command
    params = self.i2c.i2c_read([], reply_len)
  File "/home/pi/klipper/klippy/extras/bus.py", line 250, in i2c_read
    return self.i2c_read_cmd.send([self.oid, write, read_len])
  File "/home/pi/klipper/klippy/mcu.py", line 96, in send
    return self._do_send([self._cmd.encode(data)], minclock, reqclock)
  File "/home/pi/klipper/klippy/mcu.py", line 93, in _do_send
    raise self._error(str(e))
klippy.gcode.CommandError: Unable to obtain 'i2c_read_response' response
BME280: Error reading data
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/mcu.py", line 91, in _do_send
    return xh.get_response(cmds, self._cmd_queue, minclock, reqclock)
  File "/home/pi/klipper/klippy/serialhdl.py", line 506, in get_response
    raise error("Unable to obtain '%s' response" % (self.name,))
klippy.serialhdl.error: Unable to obtain 'i2c_read_response' response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/bme280.py", line 468, in _sample_bme280
    data = self.read_register("PRESSURE_MSB", 8)
  File "/home/pi/klipper/klippy/extras/bme280.py", line 865, in read_register
    params = self.i2c.i2c_read(regs, read_len)
  File "/home/pi/klipper/klippy/extras/bus.py", line 250, in i2c_read
    return self.i2c_read_cmd.send([self.oid, write, read_len])
  File "/home/pi/klipper/klippy/mcu.py", line 96, in send
    return self._do_send([self._cmd.encode(data)], minclock, reqclock)
  File "/home/pi/klipper/klippy/mcu.py", line 93, in _do_send
    raise self._error(str(e))
klippy.gcode.CommandError: Unable to obtain 'i2c_read_response' response
```

I believe this implementation is attempting to read the BME280's before they have been initialized.

**Comment by meteyou** [comment]
your current mod use the get_handle overwrite, which should not be in the merged version. it also doesnt need the temp from the bme280. it will fallback to 25deg per default. i think it is more a timing issue in klipper/i2c reading.

**Comment by thetic** [comment]
> your current mod use the get_handle overwrite, which should not be in the merged version. it also doesnt need the temp from the bme280. it will fallback to 25deg per default. i think it is more a timing issue in klipper/i2c reading.

Are you referring to: https://github.com/thetic/klipper-sgp40/blob/0d14f9f3fc7b335a986081a6d2fdab53b1be1651/src/klipper_sgp40/__init__.py#L134-L155? This was inherited from the original nevermore max implementation. I just [created a branch](https://github.com/thetic/klipper-sgp40/tree/cleanup) to remove that hack. I've confirmed that to boots without issue and I will continue testing it.

**Comment by thetic** [comment]
@meteyou you may be interested in this change: https://github.com/thetic/klipper-sgp40/pull/21. I haven't seen an I2C timeout yet in over a week of testing.

**Comment by meteyou** [comment]
this looks interesting! thanks for the ping. I have to double check it, but i think this should fix the issue with init errors.
